# Generated by Django 5.2.12 on 2026-04-11 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adventure',
            name='image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
